
services:

  gateway:
    image: nginx:1-alpine
    ports:
      - 8000:80
    volumes:
      - ./client/nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - ml_api
      - server
      - client
    networks:
      - localyam-app-network
  # Model
  ml_api:
    build:  
      context: ./ml_api
      dockerfile: Dockerfile.dev
    container_name: flask-server
    volumes:
      - ./ml_api/model:/app/model
    env_file:
      - .env.dev
    networks:
      - localyam-app-network
    restart: unless-stopped

  # Server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: express-server
    volumes:
      - ./server/uploads:/app/uploads
      - ./server:/app
      - /app/node_modules
    env_file:
      - .env.dev
    environment:
      CHOKIDAR_USEPOLLING: true
      WATCHPACK_POLLING: true
    depends_on:
      - ml_api
    networks:
      - localyam-app-network
    restart: unless-stopped

  # Client
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes: 
      - ./client:/app
      - /app/node_modules
    container_name: react-client
    env_file:
      - .env.dev
    depends_on:
      - server
    networks:
      - localyam-app-network
    restart: unless-stopped


# Networks
networks:
  localyam-app-network:
    driver: bridge